spring.application.name=inka-catalogo
server.port=8082

# Conexión exclusiva a MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/inka_catalogo
# Logs limpios
logging.level.pe.cibertec=INFO
logging.level.org.springframework.data.mongodb=DEBUG